### ISSUE TITLE
Google Font Listing Error

### ISSUE THREAD

**Issue by DrFretNot** [SUSE/suse-font#6]
On the page for the Google Font listing: 

[https://fonts.google.com/specimen/SUSE](https://fonts.google.com/specimen/SUSE)

The characters aren't rendered properly.

![Screenshot 2024-08-27 211648](https://github.com/user-attachments/assets/2b557ade-6390-461b-b3db-bcef379799fa)

(Windows 11, Browser - Edge)

**Comment by solmatas** [comment]
The font is not yet live in GF.
